# Header

menu:
  主页: /
  归档: /archives/index.html
  留言: /messageBoard/index.html
# SubNav
subnav:
  github: "https://github.com/Brycexxx"
  #weibo: "#"
  zhihu: "#"
  qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:xuhp1022@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  #rss: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
#excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃🍗'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: /assets/wechatpay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_tongji: true
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: https://raw.githubusercontent.com/Brycexxx/BlogComments/master/avatar1.jpg

#是否开启分享
share_jia: true

# 百度推送
baidu_push: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# gitalk评论
gitalk:
  enable:  false
  githubID:  Brycexxx   
  repo:  'BlogComments'
  ClientID:  '3afab695eef9381d5541'
  ClientSecret:  '63917335393ddb7709308a1657449674f563050c'
  adminUser:  Brycexxx
  distractionFreeMode: true

# Valine https://valine.js.org
valine: 
 appid:  'gzE0z8RUfCAd6dmjY2H00HIe-gzGzoHsz'
 appkey:  't55oLrwc8aTKChJLP1ijYzyy'
 verify: false #验证码
 notify: false #评论回复提醒
 avatar: monsterid #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
 avatar_cdn: 'https://sdn.geekzu.org/avatar/' #头像CDN
 placeholder: 由于leancloud体验实例有每天 6 小时的强制休眠时间，所以大家的评论未必能及时知晓，望谅解。
              若事情紧急，还请邮件联系，谢谢
              #评论框占位符
 pageSize: 10 #评论分页

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '搜索'
  friends: '友链'
  aboutme: '关于我'

friends:
  廖雪峰 python 教程: https://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000
  KHUM 大佬的博客: http://blogs.kuniot.top:10000/
  同济大学生活小助手: http://120.79.239.130/
  leetcode: https://leetcode-cn.com/
  Spurious Correlations: http://tylervigen.com/spurious-correlations
  Better Explained: https://betterexplained.com/


aboutme: 想知道啊😏<br><br>就不告诉你🤣<br><br>哈哈哈哈......
